name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and release
        uses: BigWigsMods/packager@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
